# Configuration file for amplitude_encoding_noise_latest.py
# Edit these values to control your experiment

# List of NIfTI files to use (absolute or relative paths)
nifti_files:
  - "data/sub-ADNI011S0003_brain.nii.gz"
  - "data/sub-ADNI022S0004_brain.nii.gz"
  - "data/sub-ADNI100S5280_brain.nii.gz"

# Range of slices to use from each file (inclusive, exclusive)
slice_range: [0, 30]  # Use fewer slices for faster diagnostic testing
intensity_threshold: 0.04     # Mean intensity threshold for slice selection
plot_slices: true            # Visualize selected slices during initialization

# K-space undersampling parameters
acceleration_factor: 4         # Undersampling factor (e.g., 2 or 4)
center_fraction: 0.08          # Fraction of center k-space to fully sample
mask_mode: "gaussian"          # Mask type: 'gaussian', 'linear', or 'uniform'
scale: 8.5                     # Scale for variable density mask

target_size: [64, 64]          # Output image size (height, width)
batch_size: 4                  # Lower batch size for Colab compatibility
num_epochs: 5                  # Number of training epochs
lr: 0.001                      # Learning rate
noise_std: 0.0                 # Stddev of classical noise (not used with depolarizing)
save_path: "output"            # Directory to save outputs and logs
model_name: "quantum_mri_test" # Name for saving model checkpoints

# Quantum encoding type: 'amplitude' or 'angle'
encoding_type: "amplitude"

# Quantum processing configuration
quantum_processing:
  parallel: true               # Enable parallel processing
  max_workers: null           # null for automatic (cpu_count - 1), or specify number
  patch_timeout: 30           # Timeout in seconds for each patch simulation
  min_patches_for_parallel: 2  # Minimum number of patches to trigger parallel processing

# Quantum noise configuration
quantum_noise:
  # Global gate errors (based on hardware-inspired values)
  gate_errors:
    h: 0.001    # Hadamard gate (single-qubit)
    ry: 0.001   # RY gate
    rz: 0.001   # RZ gate
    cx: 0.01    # CNOT gate (two-qubit)

  # Optional qubit-specific errors
  qubit_errors:
    0:  # Slightly worse on qubit 0
      h: 0.002
      ry: 0.002
      rz: 0.002
      cx: 0.015
    2:  # Slightly worse on qubit 2
      h: 0.002
      ry: 0.002
      rz: 0.002
      cx: 0.015

# Optional Parameters
use_gpu: false
num_workers: 2                # Compatible with Colab CPU/GPU
pin_memory: true
early_stopping_patience: 3    # Early stopping for small test runs
early_stopping_delta: 0.001
weight_decay: 0.0001
gradient_clip_val: 1.0
