version: "1.0.0"

data:
  # Example NIfTI files (replace with actual paths)
  nifti_files:
    - "data/brain_scan1.nii.gz"
    - "data/brain_scan2.nii.gz"
  
  # Use intensity threshold instead of slice range
  intensity_threshold: 0.04
  
  # K-space undersampling parameters
  acceleration_factor: 4
  center_fraction: 0.08
  mask_mode: "gaussian"
  scale: 8.5
  target_size: [64, 64]

model:
  # Quantum model parameters
  encoding_type: "amplitude"
  use_gpu: true
  
  # Parallel processing configuration
  parallel_processing:
    enabled: true  # Enable parallel processing for this experiment
    num_workers: 8  # Use more workers for better performance
  
  # Quantum noise configuration with higher error rates
  noise_config:
    gate_errors:
      h: 0.002    # Increased Hadamard error
      ry: 0.003   # Increased Rotation-Y error
      rz: 0.003   # Increased Rotation-Z error
      cx: 0.015   # Increased CNOT error
    # Example qubit-specific errors
    qubit_errors:
      0:  # Errors for qubit 0
        h: 0.003
        ry: 0.004
      1:  # Errors for qubit 1
        cx: 0.02

training:
  # Training parameters
  batch_size: 16  # Smaller batch size
  num_epochs: 150  # More epochs
  learning_rate: 0.0005  # Lower learning rate
  
  # Early stopping configuration
  early_stopping:
    patience: 15  # More patience
    delta: 0.0005  # Smaller delta
  
  # Optimizer configuration
  optimizer:
    type: "adam"
    weight_decay: 0.0002  # Increased weight decay
    gradient_clip_val: 0.5  # Reduced gradient clipping
  
  # Data loading parameters
  num_workers: 4
  pin_memory: true

# Output configuration
output:
  save_path: "output/experiment_1"
  model_name: "quantum_mri_experiment_1"
  tensorboard: true
  save_frequency: 5

# Experiment metadata
metadata:
  description: "Example experiment with higher noise rates and qubit-specific errors"
  tags:
    - "high_noise"
    - "qubit_specific"
    - "amplitude_encoding"
  notes: "Testing model robustness with increased noise rates" 